name: Deploy to S3

on:
  push:
    branches:
      - master  # ou a branch que você deseja usar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # ou a versão do Node.js que você está usando

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build --prod

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # região do seu bucket S3
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 sync ./dist/banco-validator/browser s3://$S3_BUCKET --delete
